[project]
name = "zimdb"
version = "0.1.0"
description = "基于PyTorch的IMDB情感分析项目"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
    "requests>=2.25.0",
    "flask>=2.0.0",
]

[project.scripts]
zimdb-train = "train:main"

[dependency-groups]
dev = []